# for github.com
approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - "zalando"

  # Allow last committer / PR creator to approve as well.
  # This will probably become the default in zappr.
  ignore: none

X-Zalando-Team: "zmon"
X-Zalando-Type: code

approvals:
  minimum: 2

commit:
  message:
    patterns: # commit message has to match any one of
      - "^ *#[0-9]+" # starts with hash and digits
