version: '3'
services:

  slr-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  slr-db:
    image: postgres:9.6.1
    ports:
       - "5432:5432"
    environment:
      POSTGRES_PASSWORD: db-password

  slr-migrate:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.migrate
    depends_on:
      - slr-db
    restart: on-failure
    environment:
      DATABASE_URI: postgresql://postgres:db-password@slr-db/slr

  slr-backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    depends_on:
      - slr-migrate
      - slr-redis
      - slr-db
    restart: on-failure
    ports:
      - "8080:8080"
    # wait until migration is done!
    command: ["sh", "-c", "sleep 5 ; python -m app.main"]
    environment:
      DATABASE_URI: postgresql://postgres:db-password@slr-db/slr
      KAIROSDB_URL: https://data-service.zmon.zalan.do/kairosdb-proxy
      # TOKENINFO_URL: https://info.services.auth.zalando.com/oauth2/tokeninfo
      SLR_PRESHARED_TOKEN: 'SLR-TOKEN'
      SLR_LOCAL_ENV: "true"
      SLR_APP_URL: http://localhost:8000
      # SESSION
      SLR_SESSION_TYPE: redis
      SLR_SESSION_REDIS_HOST: slr-redis
      # CACHE
      SLR_CACHE_TYPE: RedisCache
      SLR_CACHE_REDIS_HOST: slr-redis
      # THROTTLING
      SLR_RATE_LIMIT_STORAGE: redis://slr-redis:6379

  slr-frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    command: ["sh", "-c", "sleep 5 ; nginx"]
    restart: on-failure
    depends_on:
      - slr-backend
    ports:
      - "8000:8000"
