FROM registry.opensource.zalan.do/stups/python:latest

RUN apt-get update && apt-get install -y libssl-dev gnuplot

RUN pip3 install clickclick jinja2 stups-zign

COPY zmon_slr /

COPY dockerfiles/reports.py /reports.py

RUN chmod a+x /reports.py

WORKDIR /zmon_slr

RUN python3 setup.py install

CMD python /reports.py
